<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8"/>
  <title>チケット管理</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<div class="container">
  <h1>チケット管理</h1>
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">チケット一覧</h2>
      <div class="card-text">
        <ul class="list-group">
            <?php foreach ($tickets as $ticket): ?>
              <li class="list-group-item"><?= e($ticket['subject'], ENT_QUOTES, 'UTF-8', false) ?></li>
            <?php endforeach; ?>
        </ul>
      </div>
    </div>
  </div>
</div>
</body>
</html>
