<?= $this->fetch('header.phtml') ?>
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">チケット詳細</h2>
      <div class="card-text">
        <table class="table table-bordered">
          <thead>
          <tr>
            <th>ID</th>
            <th>件名</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><?= e($ticket['id']) ?></td>
            <td><?= e($ticket['subject']) ?></td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<?= $this->fetch('footer.phtml') ?>
